// 물류/창고 업무 플로우차트 데이터
const DEFAULT_FLOW_DATA = {
  nodes: [
    { id: 'A', group: 'A', label: '(A) 상품 입고', x: 40, y: 60, color: '#4ade80', textColor: '#1a2e1a', description: '외부로부터 상품이 창고에 도착하는 최초 단계입니다.\n\n[주요 업무]\n- 거래처 / 공급업체로부터 상품 수령\n- 입고 예정 수량과 실수령 수량 대조\n- 입고 일시 및 담당자 기록\n\n[참고사항]\n상품 입고 전 반드시 거래처 발주서(P/O)와 납품서를 사전에 확인하여 오입고를 방지합니다.' },
    { id: 'A-01', group: 'A', label: '(A-01) 입고정보 확인', x: 40, y: 180, color: '#86efac', textColor: '#1a2e1a', description: '입고된 상품의 정보를 시스템 및 서류와 대조·확인하는 단계입니다.\n\n[주요 업무]\n- 거래명세서 / 납품확인서 검토\n- 상품 코드, 품명, 수량, 유통기한 확인\n- 입고 정보 시스템 등록 (ERP / 구글 시트)\n- 불일치 항목 발생 시 거래처 즉시 통보' },
    { id: 'A-02', group: 'A', label: '(A-02) 창고 이동', x: 40, y: 320, color: '#86efac', textColor: '#1a2e1a', description: '입고 확인이 완료된 상품을 창고 내 지정 구역으로 이동하는 단계입니다.\n\n[주요 업무]\n- 지게차 / 핸드팔레트 등 운반 장비 활용\n- 품목별 보관 구역(Zone) 배정\n- 냉장·냉동 상품 온도 관리 구역 분류\n- 이송 완료 후 위치 정보 시스템 업데이트' },
    { id: 'A-03', group: 'A', label: '(A-03) 검수 및 적재', x: 40, y: 460, color: '#86efac', textColor: '#1a2e1a', description: '창고 이송 후 상품의 품질 및 수량을 최종 검수하고 선반/팔레트에 적재하는 단계입니다.\n\n[주요 업무]\n- 외관 파손, 유통기한, 라벨 상태 확인\n- 선입선출(FIFO) 원칙에 따른 적재\n- 적재 위치(Bin Location) 기록\n- 불량품 격리 및 반품 처리' },
    { id: 'A-03b', group: 'A', label: '(A-03) 입,출고 정보 작성', x: 40, y: 600, color: '#86efac', textColor: '#1a2e1a', description: '입고 및 출고 관련 정보를 공식 문서와 시스템에 기록하는 단계입니다.\n\n[주요 업무]\n- 입고 전표 / 입고 확인서 작성\n- 구글 시트 입출고 대장 업데이트\n- 재고 수량 반영\n- 입고 사진 촬영 및 보관 (필요 시)' },
    { id: 'ORDER', group: 'ORDER', label: '주문 관리', x: 300, y: 180, color: '#c084fc', textColor: '#1a0a2e', description: '전체 주문을 통합 관리하는 허브 역할의 업무입니다.\n\n[주요 업무]\n- 직영점 / 관매장 / 온라인 채널별 주문 취합\n- 주문 우선순위 설정 및 출고 스케줄 조율\n- 재고 현황 확인 후 출고 가능 여부 판단\n- PDF 파일(주문서/피킹리스트) 각 담당자에게 전달' },
    { id: 'B', group: 'ORDER', label: '(B) 재고 확인', x: 300, y: 460, color: '#a78bfa', textColor: '#1a0a2e', description: '현재 창고 내 재고 수량과 위치를 실시간으로 확인하는 단계입니다.\n\n[주요 업무]\n- 품목별 현재 재고 수량 조회\n- 안전재고 미달 품목 알림\n- 재고 위치(Bin Location) 확인\n- 출고 가능 재고와 예약 재고 구분' },
    { id: 'C', group: 'C', label: '(C) 직영 및 관매장', x: 560, y: 180, color: '#22d3ee', textColor: '#0a1f2e', description: '직영점 및 관련 매장으로의 출고를 담당하는 채널 분기 노드입니다.\n\n[주요 업무]\n- 직영점별 주문 요청 접수\n- 관매장 납품 일정 확인\n- 주문 관리 시스템에서 PDF 피킹리스트 수신\n- 출고 우선순위 결정' },
    { id: 'C-01', group: 'C', label: '(C-01) 라벨지 및 스케줄표 출력', x: 560, y: 320, color: '#67e8f9', textColor: '#0a1f2e', description: '출고에 필요한 라벨지와 배송 스케줄표를 출력하는 단계입니다.\n\n[주요 업무]\n- 품목별 바코드/QR 라벨 출력\n- 배송처 주소 라벨 출력\n- 출고 스케줄표(날짜별/매장별) 인쇄\n- 피킹 작업자에게 리스트 배부' },
    { id: 'C-02', group: 'C', label: '(C-02) 포장', x: 560, y: 460, color: '#67e8f9', textColor: '#0a1f2e', description: '출고할 상품을 포장하는 단계입니다.\n\n[주요 업무]\n- 피킹리스트에 따른 상품 피킹(집품)\n- 박스 포장 및 테이핑\n- 완충재(에어캡, 스티로폼 등) 사용\n- 라벨 부착 및 송장 삽입/부착' },
    { id: 'C-03', group: 'C', label: '(C-03) 검수', x: 560, y: 600, color: '#67e8f9', textColor: '#0a1f2e', description: '포장 완료된 상품을 출고 전 최종 검수하는 단계입니다.\n\n[주요 업무]\n- 포장 상태 및 라벨 정확성 확인\n- 수량 재확인 (피킹리스트 대조)\n- 파손 여부 확인\n- 검수 완료 표시 (스티커 또는 서명)' },
    { id: 'C-04', group: 'C', label: '(C-04) 분류 및 적재', x: 560, y: 740, color: '#67e8f9', textColor: '#0a1f2e', description: '검수 완료된 상품을 배송처별로 분류하고 차량에 적재하는 단계입니다.\n\n[주요 업무]\n- 배송지역별 분류 (부산, 서울, 기타)\n- 배송 차량별 적재 구역 지정\n- 무게 및 부피 고려한 적재 순서 결정\n- 적재 완료 수량 시스템 반영' },
    { id: 'C-05', group: 'C', label: '(C-05) 출고 대기', x: 560, y: 880, color: '#67e8f9', textColor: '#0a1f2e', description: '배송 차량 도착 전까지 출고 준비 완료 상태로 대기하는 단계입니다.\n\n[주요 업무]\n- 출고 준비 완료 상태 시스템 업데이트\n- 배송 기사 / 매니저 출발 시간 확인\n- 마지막 수량 점검\n- 상차 지원' },
    { id: 'D', group: 'D', label: '(D) 온라인 주문', x: 820, y: 180, color: '#facc15', textColor: '#2e1a00', description: '온라인 채널(쇼핑몰, 오픈마켓 등)을 통해 들어오는 주문을 처리하는 시작 단계입니다.\n\n[주요 채널]\n- 자사몰 / 스마트스토어\n- 쿠팡, 11번가, G마켓 등 오픈마켓' },
    { id: 'D-01', group: 'D', label: '(D-01) 주문 수집', x: 820, y: 320, color: '#fde047', textColor: '#2e1a00', description: '각 온라인 채널의 주문을 한 곳에 모아 통합 관리하는 단계입니다.\n\n[주요 업무]\n- 채널별 주문 다운로드\n- 주문 데이터 정제 및 중복 확인\n- 품절/재고 부족 주문 분리\n- 합포장 주문 처리' },
    { id: 'D-02', group: 'D', label: '(D-02) 송장 출력', x: 820, y: 460, color: '#fde047', textColor: '#2e1a00', description: '수집된 온라인 주문에 대해 택배 송장을 출력하는 단계입니다.\n\n[주요 업무]\n- 택배사 연동 송장 번호 자동 발급\n- 송장 스티커 출력 (감열지 라벨프린터)\n- 채널별 운송장 번호 업로드\n- 출력된 송장을 포장 팀에 전달' },
    { id: 'D-03', group: 'D', label: '(D-03) 출고 시트 작성', x: 820, y: 600, color: '#fde047', textColor: '#2e1a00', description: '온라인 주문 출고 현황을 정리한 출고 시트를 작성하는 단계입니다.\n\n[주요 업무]\n- 일자별 출고 현황 구글 시트 작성\n- 채널별 / 품목별 출고 수량 집계\n- 미출고 건 사유 기록\n- 출고 완료 확인 후 관련 팀 공유' },
    { id: 'E', group: 'E', label: '(E) 부상판매', x: 1080, y: 600, color: '#fb923c', textColor: '#2e0a00', description: '기획전, 행사, 사은품 등 부수적인 판매 행위(부상판매)를 관리하는 단계입니다.\n\n[주요 업무]\n- 사은품 / 번들 상품 구성 확인\n- 행사 조건 충족 여부 점검\n- 부상 상품 별도 피킹 지시' },
    { id: 'E-02', group: 'E', label: '(E-02) 수기(상품 확인)', x: 1080, y: 740, color: '#fdba74', textColor: '#2e0a00', description: '부상판매 상품을 수기로 직접 확인하는 단계입니다.\n\n[주요 업무]\n- 부상 상품 종류 및 수량 수기 기록\n- 실물 상품과 기록 대조 확인\n- 보상 조건 충족 주문 리스트 수기 작성\n- 확인 후 분류 및 적재 단계(C-04)로 전달' },
    { id: 'F', group: 'F', label: '(F) 폐기 처리', x: 40, y: 780, color: '#f87171', textColor: '#2e0000', description: '유통기한 만료, 파손, 품질 불량 등의 사유로 폐기가 필요한 상품을 처리하는 단계입니다.\n\n[폐기 사유]\n- 유통기한 초과\n- 외관 파손 / 내용물 손상\n- 품질 불량 (생산 클레임)\n- 반품 후 재판매 불가 판정' },
    { id: 'F-01', group: 'F', label: '(F-01) 폐기 품목 선정', x: 40, y: 920, color: '#fca5a5', textColor: '#2e0000', description: '폐기 대상 품목을 선정하고 목록을 작성하는 단계입니다.\n\n[주요 업무]\n- 재고 실사 중 폐기 대상 식별\n- 유통기한 임박 상품 정기 점검\n- 폐기 품목 리스트 작성\n- 담당 매니저 승인 요청' },
    { id: 'F-02', group: 'F', label: '(F-02) 폐기 업체 선정', x: 40, y: 1060, color: '#fca5a5', textColor: '#2e0000', description: '폐기를 전문적으로 처리할 업체를 선정하는 단계입니다.\n\n[주요 업무]\n- 등록된 폐기 업체 목록에서 선정\n- 폐기 일정 및 비용 협의\n- 폐기 위탁 계약서 / 확인서 준비' },
    { id: 'F-04', group: 'F', label: '(F-04) 출고(폐기 업체)', x: 40, y: 1200, color: '#fca5a5', textColor: '#2e0000', description: '폐기 업체로 폐기 상품을 인계하는 최종 단계입니다.\n\n[주요 업무]\n- 폐기 상품 포장 및 분리\n- 폐기 확인서 작성 및 서명\n- 폐기 업체 차량에 상차\n- 폐기 처리 완료 후 재고에서 차감' },
    { id: 'G', group: 'G', label: '(G) A/S 및 반품 입고', x: 300, y: 780, color: '#eab308', textColor: '#2e1a00', description: '고객 또는 매장으로부터 반품되거나 A/S 요청된 상품이 창고에 입고되는 단계입니다.\n\n[반품 유형]\n- 고객 변심 반품\n- 상품 불량 반품\n- 배송 사고 반품\n- A/S 요청 상품' },
    { id: 'G-01', group: 'G', label: '(G-01) 구글 시트 작성', x: 300, y: 920, color: '#fde047', textColor: '#2e1a00', description: '반품/A/S 입고 내역을 구글 시트에 체계적으로 기록하는 단계입니다.\n\n[기록 항목]\n- 반품 일자, 주문번호\n- 상품명, 수량\n- 반품 사유\n- 상품 상태 (재판매 가능/불가)' },
    { id: 'OUT-BUSAN', group: 'OUT', label: '출고 (부산 직영 매니저)', x: 300, y: 1060, color: '#94a3b8', textColor: '#0f172a', description: '부산 직영점 매니저가 직접 수령하는 출고 방식입니다.' },
    { id: 'OUT-ISA', group: 'OUT', label: '출고 (이사탁배)', x: 300, y: 1180, color: '#94a3b8', textColor: '#0f172a', description: '이사탁배 배송 서비스를 이용한 출고 방식입니다.' },
    { id: 'OUT-SEOUL', group: 'OUT', label: '출고 (서울 직영 매니저)', x: 560, y: 1060, color: '#94a3b8', textColor: '#0f172a', description: '서울 직영점 매니저가 직접 수령하는 출고 방식입니다.' },
    { id: 'OUT-HWA', group: 'OUT', label: '출고 (한진택배)', x: 560, y: 1180, color: '#94a3b8', textColor: '#0f172a', description: '한진택배 배송 서비스를 이용한 출고 방식입니다.' }
  ],
  edges: [
    { id: 'e1',  from: 'A',     to: 'A-01',      label: '' },
    { id: 'e2',  from: 'A-01',  to: 'A-02',      label: '' },
    { id: 'e3',  from: 'A-02',  to: 'A-03',      label: '' },
    { id: 'e4',  from: 'A-03',  to: 'A-03b',     label: '' },
    { id: 'e5',  from: 'A-03b', to: 'B',          label: '입고 정보 전달' },
    { id: 'e6',  from: 'A-01',  to: 'ORDER',     label: '', bidirectional: true },
    { id: 'e7',  from: 'ORDER', to: 'C',          label: 'PDF 파일 전달' },
    { id: 'e8',  from: 'ORDER', to: 'B',          label: '', bidirectional: true },
    { id: 'e9',  from: 'C',     to: 'C-01',      label: '' },
    { id: 'e10', from: 'C-01',  to: 'C-02',      label: '' },
    { id: 'e11', from: 'C-02',  to: 'C-03',      label: '' },
    { id: 'e12', from: 'C-03',  to: 'C-04',      label: '' },
    { id: 'e13', from: 'B',     to: 'C-04',      label: '재고 정보' },
    { id: 'e14', from: 'C-04',  to: 'C-05',      label: '' },
    { id: 'e15', from: 'C-05',  to: 'OUT-BUSAN', label: '' },
    { id: 'e16', from: 'C-05',  to: 'OUT-ISA',   label: '' },
    { id: 'e17', from: 'C-05',  to: 'OUT-SEOUL', label: '' },
    { id: 'e18', from: 'C-05',  to: 'OUT-HWA',   label: '' },
    { id: 'e19', from: 'D',     to: 'D-01',      label: '' },
    { id: 'e20', from: 'D-01',  to: 'D-02',      label: '' },
    { id: 'e21', from: 'D-02',  to: 'C-02',      label: '송장 전달 (Check)' },
    { id: 'e22', from: 'D-02',  to: 'D-03',      label: '' },
    { id: 'e23', from: 'D-03',  to: 'E',          label: '' },
    { id: 'e24', from: 'E',     to: 'E-02',      label: '' },
    { id: 'e25', from: 'E-02',  to: 'C-04',      label: '' },
    { id: 'e26', from: 'F',     to: 'F-01',      label: '' },
    { id: 'e27', from: 'F-01',  to: 'F-02',      label: '' },
    { id: 'e28', from: 'F-02',  to: 'F-04',      label: '' },
    { id: 'e29', from: 'G',     to: 'G-01',      label: '' },
    { id: 'e30', from: 'G-01',  to: 'F',          label: '폐기 이관' },
    { id: 'e31', from: 'G-01',  to: 'B',          label: '재입고' }
  ]
};

const GROUP_COLORS = {
  'A':     { bg: '#4ade80', text: '#1a2e1a', name: '입고 프로세스' },
  'ORDER': { bg: '#c084fc', text: '#1a0a2e', name: '주문/재고 관리' },
  'C':     { bg: '#22d3ee', text: '#0a1f2e', name: '직영/관매장 출고' },
  'D':     { bg: '#facc15', text: '#2e1a00', name: '온라인 주문' },
  'E':     { bg: '#fb923c', text: '#2e0a00', name: '보상판매' },
  'F':     { bg: '#f87171', text: '#2e0000', name: '폐기 처리' },
  'G':     { bg: '#eab308', text: '#2e1a00', name: 'A/S 및 반품' },
  'OUT':   { bg: '#94a3b8', text: '#0f172a', name: '출고 완료' }
};
